version: "3.9"

services: 
    web:
        container_name: "idem-api"
        image: "idem-api"
        build: 
            context: .
            dockerfile:  ./Dockerfile
        ports: 
            - "3001:3001"
        environment: 
            - PORT=3001
            - MESSAGEBIRD_KEY="x"
            - SUPPORT_EMAIL_ADDRESS="support@dltx.io"
            - SUPPORT_EMAIL_PASSWORD="x"
            - ETH_SEED=cream olive tissue below crunch convince blame helmet mistake achieve blanket talent
            - ETH_PRIVATE_KEY=32740a305605a59964aeed912389dcc93e5ba657f00979480b093fee2b753356
            - PGP_PRIVATE_KEY="./info.asc"
            - PGP_PRIVATE_KEY_PASSWORD="Test1234"
            - CIPHER_SECRET="Test1234"
